# Generated by Django 5.2.4 on 2026-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
